# **Naive Bayes**
In this code I have used Naive Bayes Model to Predict whether Passenger on Titanic will survive or not.

In [92]:
#Importing Required Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score, f1_score
from sklearn.metrics import confusion_matrix, recall_score, classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

np.set_printoptions(precision=4, linewidth=100)

import warnings
warnings.filterwarnings('ignore')

In [93]:
#Importing the Dataset
df = pd.read_csv("/content/Titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Name         891 non-null    object 
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
 11  Survived     891 non-null    int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [95]:
#Dropping non-usable features
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis = 'columns', inplace = True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [96]:
#Defining Dependent and Independent Variables i.e. 'Y' and 'x' resp.
y = df['Survived']
X = df.drop('Survived', axis = 'columns')

In [97]:
dummies = pd.get_dummies(X.Sex)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [98]:
X = pd.concat([X, dummies], axis = 'columns')
X.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [99]:
# Dropping sex column and male column
X.drop(['Sex', 'male'], axis = 'columns', inplace = True)
X.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [100]:
#Checking Missing Values
X.columns[X.isna().any()]

Index(['Age'], dtype='object')

In [101]:
X.Age[ : 10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [102]:
#Changing Missing Values with mean of Age column
X.Age = X.Age.fillna(X.Age.mean())
X.head(10)

Pclass        Age     Fare  female
0       3  22.000000   7.2500       0
1       1  38.000000  71.2833       1
2       3  26.000000   7.9250       1
3       1  35.000000  53.1000       1
4       3  35.000000   8.0500       0
5       3  29.699118   8.4583       0
6       1  54.000000  51.8625       0
7       3   2.000000  21.0750       0
8       3  27.000000  11.1333       1
9       2  14.000000  30.0708       1

In [146]:
#Now we split the data for training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [147]:
#Applying Model
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [148]:
model.score(X_test, y_test)

0.8100558659217877

In [106]:
X_test[0 : 10]

Pclass        Age      Fare  female
581       1  39.000000  110.8833       1
860       3  41.000000   14.1083       0
457       1  29.699118   51.8625       1
41        2  27.000000   21.0000       1
227       3  20.500000    7.2500       0
307       1  17.000000  108.9000       1
855       3  18.000000    9.3500       1
148       2  36.500000   26.0000       0
513       1  54.000000   59.4000       1
322       2  30.000000   12.3500       1

In [107]:
y_test[0 : 10]

581    1
860    0
457    1
41     0
227    0
307    1
855    1
148    0
513    1
322    1
Name: Survived, dtype: int64

In [108]:
#Making Prediciton
y_pred = model.predict(X_test)
y_pred

array([1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1])

In [109]:
model.predict_proba(X_test)

array([[2.1253e-03, 9.9787e-01],
       [9.6991e-01, 3.0094e-02],
       [5.0750e-02, 9.4925e-01],
       [2.5001e-01, 7.4999e-01],
       [9.6281e-01, 3.7193e-02],
       [1.9025e-03, 9.9810e-01],
       [3.8524e-01, 6.1476e-01],
       [9.3257e-01, 6.7432e-02],
       [3.7779e-02, 9.6222e-01],
       [2.5836e-01, 7.4164e-01],
       [9.6724e-01, 3.2759e-02],
       [9.6839e-01, 3.1612e-02],
       [7.0450e-01, 2.9550e-01],
       [6.8400e-01, 3.1600e-01],
       [1.6171e-02, 9.8383e-01],
       [9.6745e-01, 3.2554e-02],
       [9.2598e-01, 7.4024e-02],
       [1.3402e-02, 9.8660e-01],
       [9.6694e-01, 3.3056e-02],
       [9.6517e-01, 3.4828e-02],
       [9.6329e-01, 3.6711e-02],
       [2.3890e-01, 7.6110e-01],
       [9.6276e-01, 3.7237e-02],
       [9.2595e-01, 7.4046e-02],
       [1.2991e-02, 9.8701e-01],
       [6.4407e-01, 3.5593e-01],
       [9.6380e-01, 3.6203e-02],
       [9.6065e-01, 3.9355e-02],
       [2.5424e-01, 7.4576e-01],
       [6.9442e-09, 1.0000e+00],
       [9.

In [110]:
#Checking Accuracy
cm = confusion_matrix(y_test, y_pred)
print (cm)
print(f1_score(y_test, y_pred))

[[88 21]
 [21 49]]
0.7


In [111]:
print(accuracy_score(y_test, y_pred))

0.7653631284916201


In [112]:
print( metrics.classification_report( y_test, y_pred ) )

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       109
           1       0.70      0.70      0.70        70

    accuracy                           0.77       179
   macro avg       0.75      0.75      0.75       179
weighted avg       0.77      0.77      0.77       179

